# Generated by Django 2.2.5 on 2019-12-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191229_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='currecy',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='langauge',
            new_name='language',
        ),
    ]
