# Generated by Django 2.2.5 on 2020-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200102_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('confirmed', 'confirmed'), ('pending', 'pending')], default='pending', max_length=12),
        ),
    ]
