# Generated by Django 2.2.5 on 2020-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200103_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('canceled', 'canceled'), ('pending', 'pending')], default='pending', max_length=12),
        ),
    ]
